---
- name: Install grafana dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - adduser
    - libfontconfig1

- name: Create grafana temporary directory
  ansible.builtin.file:
    path: /tmp/grafana/
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Download Grafana tarball
  ansible.builtin.get_url:
    url: https://dl.grafana.com/oss/release/grafana_9.0.5_amd64.deb 
    dest: /tmp/grafana/grafana_9.0.5_amd64.deb
    mode: '0755'

- name: Install grafana package
  apt: deb="/tmp/grafana/grafana_9.0.5_amd64.deb"

- name: Reload systemd configuration
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable and start grafana service
  ansible.builtin.systemd:
    state: started
    enabled: yes
    name: grafana-server

      #- name: Retrieve Grafana url
      #  ansible.builtin.debug:
      #   var: hostvars[inventory_hostname]['groups']['grafana'][0]
      #  register: grafanaip
      #
      #- name: show grafanaip value
      #  debug: 
      #    msg: "{{ grafanaip.stdout }}"
      #
      #- name: Update admin password
      #  community.grafana.grafana_user:
      #    url: "http://{{ grafanaip }}:3000"
      #    url_username: admin
      #    url_password: admin
      #    name: "Bruce Wayne"
      #    email: batman@gotham.city
      #    login: batman
      #    password: robin
      #    is_admin: true
      #    state: present
