---
- name: Install grafana dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - adduser
    - libfontconfig1

- name: Create grafana temporary directory
  ansible.builtin.file:
    path: /tmp/grafana/
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Download Grafana tarball
  ansible.builtin.get_url:
    url: https://dl.grafana.com/oss/release/grafana_9.0.5_amd64.deb 
    dest: /tmp/grafana/grafana_9.0.5_amd64.deb
    mode: '0755'

- name: Install grafana package
  apt: deb="/tmp/grafana/grafana_9.0.5_amd64.deb"

- name: Reload systemd configuration
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable and start grafana service
  ansible.builtin.systemd:
    state: started
    enabled: yes
    name: grafana-server