---
- name: Create node exporter temporary directory
  ansible.builtin.file:
    path: /tmp/nexporter/
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Download node exporter tarball
  ansible.builtin.get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.4.0-rc.0/node_exporter-1.4.0-rc.0.linux-amd64.tar.gz
    dest: /tmp/nexporter/node_exporter-1.4.0-rc.0.linux-amd64.tar.gz
    mode: '0755'

- name: Untar node exporter tarball
  ansible.builtin.unarchive:
    remote_src: yes
    src: /tmp/nexporter/node_exporter-1.4.0-rc.0.linux-amd64.tar.gz
    dest: /tmp/nexporter/

- name: Create node exporter group
  ansible.builtin.group:
    name: node_exporter
    state: present

- name: Create Prometheus User
  ansible.builtin.user:
    name: node_exporter
    shell: /sbin/nologin
    groups: node_exporter
    append: yes
    create_home: False
    state: present
  
- name: Copy node exporter binaries to path
  ansible.builtin.copy:
    remote_src: yes 
    src: /tmp/nexporter/node_exporter-1.4.0-rc.0.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    owner: node_exporter
    group: node_exporter
    mode: '0744'

- name: Create node exporter systemd unit file
  ansible.builtin.template:
    src: templates/node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd configuration
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable and start node exporter service
  ansible.builtin.systemd:
    state: started
    enabled: yes
    name: node_exporter