apiVersion: v1
kind: Service 
metadata:
  name: kafka-exporter
  namespace: onl
  labels:
      k8s-app: kafka
      type: kafka-exporter
spec: 
  type: ClusterIP
  ports:
   - name: http
     targetPort: 9404
     port: 9404
  selector: 
    app.kubernetes.io/name: kafka-exporter
    strimzi.io/name: onl-kafka-exporter