apiVersion: v1
kind: Service 
metadata:
  name: zookeeper-jmx
  namespace: onl
  labels:
      type: zookeeper
spec: 
  type: ClusterIP
  ports:
   - name: http
     targetPort: 9404
     port: 9404
  selector: 
    app.kubernetes.io/name: zookeeper
    strimzi.io/kind: Kafka